// Compiles src/ui/plica.css → src/ui/plica.generated.css with Tailwind v4,
// scanning Plica's own sources for class candidates. See plica.css for why.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "@tailwindcss/node";
import { Scanner } from "@tailwindcss/oxide";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const input = resolve(root, "src/ui/plica.css");
const output = resolve(root, "src/ui/plica.generated.css");

const compiler = await compile(readFileSync(input, "utf8"), {
  base: dirname(input),
  onDependency: () => {},
});
const scanner = new Scanner({
  sources: compiler.sources.length ? compiler.sources : [{ base: dirname(input), pattern: "**/*", negated: false }],
});
const candidates = scanner.scan();
const css = compiler.build(candidates);
writeFileSync(output, `/* generated by scripts/build-css.mjs — do not edit */\n${css}`);
console.log(`plica.generated.css: ${candidates.length} candidates, ${css.length} bytes`);
