// Compiles src/ui/plica.css → src/ui/plica.generated.css with Tailwind v4,
// scanning Plica's own sources for class candidates. See plica.css for why.
//
// The output is then filtered against the HOST's compiled stylesheet: any
// utility Paperclip already ships is dropped from Plica's sheet.
//
// Why the filter is load-bearing: styles.ts appends Plica's <style> to <head>,
// so it lands AFTER the host stylesheet. Tailwind emits every scanned
// candidate, including bare utilities the host also defines (`.hidden`,
// `.flex`, `.block`). A duplicate `.hidden{display:none}` then outranks the
// host's `@media(min-width:40rem){.sm\:flex{display:flex}}` on document order
// -- equal specificity, same cascade layer -- silently breaking Paperclip's
// `hidden sm:flex` idiom and stranding every desktop-only element in its
// mobile layout.
//
// Ordering cannot fix this: appended last, Plica's duplicates beat the host's
// responsive variants; inserted first, Plica's @layer names are declared ahead
// of the host's, which pushes the host's `components` layer AFTER `utilities`
// and wrecks component styling app-wide. Dropping the duplicates removes the
// collision entirely and leaves only what Plica actually needs -- the
// utilities the host happens not to use.
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import { compile } from "@tailwindcss/node";
import { Scanner } from "@tailwindcss/oxide";
import postcss from "postcss";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const input = resolve(root, "src/ui/plica.css");
const output = resolve(root, "src/ui/plica.generated.css");

/** Largest .css in the host's built assets dir — that's the app stylesheet. */
function findHostCss() {
  if (process.env.PLICA_HOST_CSS) return process.env.PLICA_HOST_CSS;
  const dir = join(homedir(), "paperclip", "ui", "dist", "assets");
  if (!existsSync(dir)) return null;
  const css = readdirSync(dir)
    .filter((f) => f.endsWith(".css"))
    .map((f) => join(dir, f))
    .sort((a, b) => statSync(b).size - statSync(a).size);
  return css[0] ?? null;
}

const hostCssPath = findHostCss();
if (!hostCssPath || !existsSync(hostCssPath)) {
  // Fail loudly. Emitting the unfiltered sheet would silently reintroduce the
  // cascade collision described above.
  throw new Error(
    "build-css: host stylesheet not found. Set PLICA_HOST_CSS to Paperclip's " +
      "compiled CSS (ui/dist/assets/index-*.css). Refusing to emit an " +
      "unfiltered sheet, which would break the host's `hidden sm:flex` idiom.",
  );
}

const compiler = await compile(readFileSync(input, "utf8"), {
  base: dirname(input),
  onDependency: () => {},
});
const scanner = new Scanner({
  sources: compiler.sources.length ? compiler.sources : [{ base: dirname(input), pattern: "**/*", negated: false }],
});
const candidates = scanner.scan();
const built = compiler.build(candidates);

// Every class selector the host already defines.
const hostSelectors = new Set();
postcss.parse(readFileSync(hostCssPath, "utf8")).walkRules((rule) => {
  for (const sel of rule.selectors) hostSelectors.add(sel.trim());
});

let dropped = 0;
const ast = postcss.parse(built);
ast.walkRules((rule) => {
  // Only class utilities are candidates for removal. Element/:root/attribute
  // rules are left alone: those carry Plica's own scaffolding, and the host
  // defining a same-named selector does not make them redundant.
  const keep = rule.selectors.filter((sel) => {
    const s = sel.trim();
    if (!s.startsWith(".")) return true;
    if (!hostSelectors.has(s)) return true;
    dropped += 1;
    return false;
  });
  if (keep.length === 0) rule.remove();
  else if (keep.length !== rule.selectors.length) rule.selectors = keep;
});
// Sweep at-rule blocks (@media/@layer/@supports) left empty by the filter.
let swept = 1;
while (swept) {
  swept = 0;
  ast.walkAtRules((at) => {
    if (at.nodes && at.nodes.length === 0) {
      at.remove();
      swept += 1;
    }
  });
}

const css = ast.toString();
writeFileSync(output, `/* generated by scripts/build-css.mjs — do not edit */\n${css}`);
console.log(
  `plica.generated.css: ${candidates.length} candidates, ${css.length} bytes ` +
    `(${dropped} host-duplicate selectors dropped, host: ${hostCssPath})`,
);
